services:
  webapp5:
    image: igossoudarev/webdocker111124:linux
    container_name: user14_webapp
    networks:
      - webnetwork

  nginx:
    image: nginx:latest
    container_name: user14_sidecar
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "14443:443" # HTTPS
    networks:
      - webnetwork
    depends_on:
      - webapp5

networks:
  webnetwork:
    external: true
    name: magistr-web